version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
      timezone: Africa/Douala
    open-pull-requests-limit: 10
    groups:
      next:
        patterns:
          - 'next'
          - 'next-*'
          - '@next/*'
          - 'eslint-config-next'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      nestjs:
        patterns:
          - '@nestjs/*'
          - 'nestjs-*'
      mui:
        patterns:
          - '@mui/*'
          - '@emotion/*'
      react-admin:
        patterns:
          - 'react-admin'
          - 'ra-*'
      prisma:
        patterns:
          - 'prisma'
          - '@prisma/*'
      types:
        patterns:
          - '@types/*'
    commit-message:
      prefix: chore(deps)
      include: scope

  - package-ecosystem: github-actions
    directory: '/'
    target-branch: develop
    schedule:
      interval: monthly
    commit-message:
      prefix: chore(actions)
